
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgenerator
  labels:
    app: trafficgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgenerator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: trafficgenerator
    spec:
      containers:
        - name: trafficgenerator
          image: williamyeh/wrk
          command: ["wrk", "-t200", "-c5000", "-d2000m", "http://service1:9999/"]